namespace Mentis.AI.Sdk;

/// <summary>Author of a chat message.</summary>
public enum MessageRole
{
    /// <summary>Not set or not known to this SDK version.</summary>
    Unknown = 0,

    /// <summary>Written by the user.</summary>
    User = 1,

    /// <summary>Generated by the model.</summary>
    Assistant = 2,

    /// <summary>System message.</summary>
    System = 3,
}

/// <summary>A document passage an assistant answer is based on.</summary>
public sealed record Citation
{
    /// <summary>Id of the cited document.</summary>
    public required string DocumentId { get; init; }

    /// <summary>Id of the cited chunk.</summary>
    public required string ChunkId { get; init; }

    /// <summary>The cited text.</summary>
    public required string Snippet { get; init; }

    /// <summary>
    /// Title of the cited document. Only populated on messages returned directly by
    /// <see cref="IConversationsClient.SendMessageAsync"/>; <see langword="null"/> when read back later.
    /// </summary>
    public string? DocumentTitle { get; init; }
}

/// <summary>A message within a conversation.</summary>
public sealed record ChatMessage
{
    /// <summary>Message id.</summary>
    public required string Id { get; init; }

    /// <summary>Author of the message.</summary>
    public required MessageRole Role { get; init; }

    /// <summary>Message text.</summary>
    public required string Content { get; init; }

    /// <summary>When the message was created.</summary>
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>Document passages the message is based on (assistant messages only).</summary>
    public required IReadOnlyList<Citation> Citations { get; init; }
}

/// <summary>A conversation including its messages.</summary>
public sealed record Conversation
{
    /// <summary>Conversation id.</summary>
    public required string Id { get; init; }

    /// <summary>Display title.</summary>
    public required string Title { get; init; }

    /// <summary>When the conversation was started.</summary>
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>Documents the conversation draws its answers from.</summary>
    public required IReadOnlyList<string> LinkedDocumentIds { get; init; }

    /// <summary>Messages in chronological order.</summary>
    public required IReadOnlyList<ChatMessage> Messages { get; init; }

    /// <summary>Owning tenant.</summary>
    public required string TenantId { get; init; }

    /// <summary>End user owning the conversation; <see langword="null"/> for a tenant-global conversation.</summary>
    public string? OwnerUserId { get; init; }
}

/// <summary>A conversation without its messages, as returned by list operations.</summary>
public sealed record ConversationSummary
{
    /// <summary>Conversation id.</summary>
    public required string Id { get; init; }

    /// <summary>Display title.</summary>
    public required string Title { get; init; }

    /// <summary>When the conversation was started.</summary>
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>Documents the conversation draws its answers from.</summary>
    public required IReadOnlyList<string> LinkedDocumentIds { get; init; }

    /// <summary>Number of messages in the conversation.</summary>
    public required int MessageCount { get; init; }

    /// <summary>Owning tenant.</summary>
    public required string TenantId { get; init; }

    /// <summary>End user owning the conversation; <see langword="null"/> for a tenant-global conversation.</summary>
    public string? OwnerUserId { get; init; }
}
